import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Prasanth',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Kishore',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id:'1',
      name: 'MuscleBlaze whey Protien',
      slug: 'muscleblaze-whey-protien',
      category: 'whey protien',
      image: '/images/p1.webp',
      price: 4500,
      countInStocks: 10,
      brand: 'MuscleBlaze',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id:'2',
      name: 'MuscleBlaze Creatine',
      slug: 'muscleblaze-creatine',
      category: 'Creatine',
      image: '/images/p2.jpg',
      price: 450,
      countInStocks:0,
      brand: 'MuscleBlaze',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id:'3',
      name: 'MuscleBlaze Mass Gainer',
      slug: 'muscleblaze-mass-gainer',
      category: 'Mass Gainer',
      image: '/images/p3.jpg',
      price: 6500,
      countInStocks: 30,
      brand: 'MuscleBlaze',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id:'4',
      name: 'MuscleBlaze Peanut Butter',
      slug: 'muscleBlaze-peanut-butter',
      category: 'Peanut Butter',
      image: '/images/p4.jpg',
      price: 750,
      countInStocks: 10,
      brand: 'MuscleBlaze',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
